export enum AoiAnalyticIds {
  ANALYTIC_ONE = 1,
  ANALYTIC_TWO = 2,
  ANALYTIC_THREE = 3,
  ANALYTIC_FOUR= 4,
  ANALYTIC_FIVE= 5,
  ANALYTIC_SIX= 6,
  ANALYTIC_SEVEN= 7,
  ANALYTIC_EIGHT= 8,
  ANALYTIC_NINE= 9,
  ANALYTIC_TEN= 10,
}
